[tool.ruff] # https://docs.astral.sh/ruff/rules/
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "E501",   # line-too-long
    "S101",   # assert
    "ANN101", # missing-type-self
    "ANN102", # missing-type-cls
    "T20",    # flake8-print
    "COM",    # flake8-commas
    "ISC001", # single-line-implicit-string-concatenation
]

[tool.ruff.lint.pydocstyle] # https://docs.astral.sh/ruff/settings/#lintpydocstyle
convention = "google"
