# This file was automatically generated by scripts/update_sources.py
target_sources(${PROJECT_NAME} PRIVATE
    libtcod-fov/bresenham_c.c
    libtcod-fov/error.c
    libtcod-fov/fov_c.c
    libtcod-fov/fov_circular_raycasting.c
    libtcod-fov/fov_diamond_raycasting.c
    libtcod-fov/fov_permissive2.c
    libtcod-fov/fov_recursive_shadowcasting.c
    libtcod-fov/fov_restrictive.c
    libtcod-fov/fov_symmetric_shadowcast.c
    libtcod-fov/logging.c
    libtcod-fov/utility.h
)
install(FILES
    ../include/libtcod-fov.h
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/.
    COMPONENT IncludeFiles
)
install(FILES
    ../include/libtcod-fov/bresenham.h
    ../include/libtcod-fov/bresenham.hpp
    ../include/libtcod-fov/config.h
    ../include/libtcod-fov/error.h
    ../include/libtcod-fov/error.hpp
    ../include/libtcod-fov/fov.h
    ../include/libtcod-fov/fov.hpp
    ../include/libtcod-fov/fov_types.h
    ../include/libtcod-fov/libtcod_int.h
    ../include/libtcod-fov/logging.h
    ../include/libtcod-fov/map.hpp
    ../include/libtcod-fov/map_inline.h
    ../include/libtcod-fov/map_types.h
    ../include/libtcod-fov/version.h
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/libtcod-fov
    COMPONENT IncludeFiles
)
